services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-advanced-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/springdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: springdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - db-data-v2:/var/lib/postgresql/data # Sử dụng volume đã định nghĩa

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672" # RabbitMQ broker port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db-data-v2: # Đây là phần định nghĩa volume và phải là một mapping (key: value)
